# 5.3 논리 및 정보 함수

In [1]:
import pandas as pd  
fruit=pd.read_excel(r"D:\works\source\chapter05\과일 주문.xlsx",sheet_name="Sheet1")
fruit

    품목   수량    단가       금액       판매일자       유통기한       비고
0   사과  100  1500   150000 2021-09-05 2021-10-31  20만원 미만
1    귤  500   500   250000 2021-09-12 2021-10-31  20만원 이상
2    배  150  2000   300000 2021-10-09 2021-11-10  20만원 이상
3   참외  250  1200   300000 2021-10-12 2021-11-10  20만원 이상
4  한라봉  100  2500   250000 2021-11-10 2021-12-10  20만원 이상
5  토마토  800  2000  1600000 2021-11-23 2021-12-10  50만원 이상
6   포도  200  3500   700000 2021-12-17 2021-12-20  50만원 이상
7   딸기  100  1200   120000 2021-12-18 2021-12-20  20만원 미만
8   망고  200  3000   600000 2021-12-20 2021-12-31  50만원 이상
9   수박  300  6000  1800000 2021-12-20 2021-12-31  50만원 이상

In [2]:
fruit=pd.read_excel(r"D:\works\source\chapter05\과일 주문.xlsx", sheet_name="Sheet1")
fruit["비고"]=""
for idx, x in enumerate(fruit["금액"]):
    if x>=500000:
        fruit["비고"].loc[idx]="50만원 이상"
    elif x>=200000:
        fruit["비고"].loc[idx]="20만원 이상"
    else:
        fruit["비고"].loc[idx]="20만원 미만"
fruit.head(6)

C:\Users\dmsco\AppData\Local\Temp\ipykernel_19680\2129280231.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit["비고"].loc[idx]="20만원 미만"
C:\Users\dmsco\AppData\Local\Temp\ipykernel_19680\2129280231.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit["비고"].loc[idx]="20만원 이상"
C:\Users\dmsco\AppData\Local\Temp\ipykernel_19680\2129280231.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit["비고"].loc[idx]="50만원 이상"

    품목   수량    단가       금액       판매일자       유통기한       비고
0   사과  100  1500   150000 2021-09-05 2021-10-31  20만원 미만
1    귤  500   500   250000 2021-09-12 2021-10-31  20만원 이상
2    배  150  2000   300000 2021-10-09 2021-11-10  20만원 이상
3   참외  250  1200   300000 2021-10-12 2021-11-10  20만원 이상
4  한라봉  100  2500   250000 2021-11-10 2021-12-10  20만원 이상
5  토마토  800  2000  1600000 2021-11-23 2021-12-10  50만원 이상